const enum ErrorCode {
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_TOO_MANY_REQUESTS = "AUTH_TOO_MANY_REQUESTS",
}

export { ErrorCode };
